export const experiences = [
  {
    heading: "IIT - Pritzker Institute | Rush University Medical Center",
    role: "Mobile App Developer",
    summary:
      "Built a mobile application for a smart-insole rehabilitation system, implemented session tracking and motion analysis workflows, and coordinated development with clinical research teams to support ACL and osteoarthritis rehabilitation studies.",
    dateLabel: "2026–Present",
    markerPosition: 48,
    labelList: [
      "Flutter",
      "Mobile App Dev",
      "Motion Analysis",
      "Clinical Research",
      "Jira",
      "Slack",
      "Rehabilitation Tech",
      "Cross-Functional Collaboration",
    ],
    metricNumber: 2,
    metricInfo: "ACL + OA use cases",
    upOrDownIcon: true,
  },
  {
    heading: "Excelerate",
    role: "Data Analyst Associate Intern",
    summary:
      "Analyzed user data and generated business insights that improved data-driven decision-making accuracy, supporting clearer reporting and stakeholder decision quality.",
    dateLabel: "2024",
    markerPosition: 33,
    labelList: [
      "Python",
      "SQL",
      "ETL",
      "Data Analysis",
      "Visualization",
      "Reporting",
      "Machine Learning",
      "Business Insights",
    ],
    metricNumber: 30,
    metricInfo: "Decision accuracy gain",
    upOrDownIcon: true,
  },
  {
    heading: "Launch Ventures",
    role: "Frontend Developer / Flutter Developer",
    summary:
      "Engineered 5+ cross-platform applications used by 10k+ users, improved UI performance through rendering and state-management optimizations, automated CI/CD pipelines, and collaborated with international clients to ship scalable mobile products.",
    dateLabel: "2022–2024",
    markerPosition: 66,
    labelList: [
      "Flutter",
      "Dart",
      "Firebase",
      "Codemagic",
      "CI/CD",
      "Node.js",
      "OOP",
      "SOLID Principles",
      "BLoC Architecture",
      "Git",
      "API Integration",
    ],
    metricNumber: 25,
    metricInfo: "UI performance gain",
    upOrDownIcon: true,
  },
  {
    heading: "MIT-FOSS",
    role: "Frontend Developer",
    summary:
      "Designed wireframes and prototypes in Figma, built responsive web interfaces, and created UML diagrams and data models to improve software planning, UI clarity, and cross-platform usability.",
    dateLabel: "2021",
    markerPosition: 58,
    labelList: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Figma",
      "UML Diagrams",
      "UI/UX Design",
      "OOP",
      "Git",
    ],
    metricNumber: 5,
    metricInfo: "Wireframes + prototypes",
    upOrDownIcon: true,
  },
];
